name = "glexec"
version = "1.0.3"
licences = ["Apache-2.0"]
description = "A Gleam wrapper for erlexec"

repository = { type = "github", user = "manveru", repo = "gleam_erlexec" }
links = []

[dependencies]
gleam_erlang = "~> 0.25"
erlexec = "~> 2.0"
gleam_stdlib = "~> 0.36"

[dev-dependencies]
erlfmt = "~> 1.3"
gleeunit = "~> 1.0"
gleam_otp = "~> 0.10"
