name = "gleam_erlexec"
version = "0.0.1"
licences = ["Apache-2.0"]
description = "A wrapper for erlexec"

repository = { type = "github", user = "manveru", repo = "gleam_erlexec" }
links = []

[dependencies]
gleam_stdlib = "~> 0.36"
gleam_erlang = "~> 0.25"
erlexec = "~> 2.0"

[dev-dependencies]
gleeunit = "~> 1.0.2"
erlfmt = "~> 1.1"
